[package]
name = "bevy_input_focus"
version = "0.16.0-dev"
edition = "2021"
description = "Keyboard focus management"
homepage = "https://bevyengine.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]
rust-version = "1.83.0"

[features]
default = ["bevy_reflect"]

## Adds runtime reflection support using `bevy_reflect`.
bevy_reflect = [
  "dep:bevy_reflect",
  "bevy_app/bevy_reflect",
  "bevy_ecs/bevy_reflect",
  "bevy_math/bevy_reflect",
]

[dependencies]
# bevy
bevy_app = { workspace = true }
bevy_ecs = { workspace = true }
bevy_input = { workspace = true }
bevy_math = { workspace = true }
bevy_window = { workspace = true }
bevy_reflect = { workspace = true, features = ["glam"], optional = true }

# other
thiserror = { version = "2", default-features = false }
tracing = { version = "0.1", default-features = false, features = ["std"] }

[dev-dependencies]
smol_str = "0.2"

[lints]
workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["-Zunstable-options", "--generate-link-to-definition"]
all-features = true
